WITH src_venue AS (SELECT * FROM {{ ref('src_venues') }})


SELECT 
DISTINCT
{{ dbt_utils.generate_surrogate_key(['VENUE_ID', 'VENUE_NAME']) }}    AS VENUE_KEY,
COALESCE(VENUE_ID, 'NA')    AS VENUE_ID,
VENUE_NAME,
COALESCE(VENUE_URL, 'NA')   AS VENUE_URL, 
COALESCE(TIMEZONE, 'NA')    AS TIMEZONE,   
COALESCE(ZIP_CODE,'NA')     AS ZIP_CODE, 
LATITUDE, 
LONGITUDE, 
COALESCE(STREET,'NA')       AS STREET, 
CITY,
COUNTRY_CODE
FROM src_venue 
WHERE VENUE_ID IS NOT NULL

UNION 

SELECT 
'NA', 'NA',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL

