WITH src_venue AS (SELECT * FROM {{ ref('src_venues') }}),
null_record AS (SELECT NULL AS VENUE_ID,NULL AS VENUE_NAME,NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL)


SELECT 
DISTINCT
{{ dbt_utils.generate_surrogate_key(['VENUE_ID', 'VENUE_NAME']) }}    AS VENUE_KEY,
COALESCE(VENUE_ID, 'NA')    AS VENUE_ID,
COALESCE(VENUE_NAME, 'NA')  AS VENUE_NAME,
COALESCE(VENUE_URL, 'NA')   AS VENUE_URL, 
COALESCE(TIMEZONE, 'NA')    AS TIMEZONE,   
COALESCE(ZIP_CODE,'NA')     AS ZIP_CODE, 
LATITUDE, 
LONGITUDE, 
COALESCE(STREET,'NA')       AS STREET, 
CITY,
COUNTRY_CODE
FROM src_venue 
WHERE VENUE_ID IS NOT NULL

UNION 

SELECT 
{{ dbt_utils.generate_surrogate_key(['VENUE_ID', 'VENUE_NAME']) }}    AS VENUE_KEY,
'NA' AS VENUE_ID, 
'NA' AS VENUE_NAME,'NA','NA','NA',NULL,NULL,'NA','NA','NA' FROM null_record
