WITH stg_venue_hist AS ( SELECT * FROM {{ source('landing_historical', 'events_hist') }})

SELECT

DISTINCT
EVENTS__VENUE__VENUE_ID             AS VENUE_ID,
EVENTS__VENUE__VENUE_NAME           AS VENUE_NAME,
EVENTS__VENUE__VENUE_URL            AS VENUE_URL, 
EVENTS__VENUE__VENUE_TIMEZONE       AS TIMEZONE,
EVENTS__VENUE__VENUE_ZIP_CODE       AS ZIP_CODE, 
EVENTS__VENUE__VENUE_LATITUDE       AS LATITUDE, 
EVENTS__VENUE__VENUE_LONGITUDE      AS LONGITUDE, 
EVENTS__VENUE__VENUE_STREET         AS STREET, 
EVENTS__VENUE__VENUE_CITY           AS CITY,
EVENTS__VENUE__VENUE_COUNTRY_CODE   AS COUNTRY_CODE


FROM stg_venue_hist
