WITH stage_events_attraction_hist as (SELECT * FROM {{ source('landing_historical', 'events_atractions') }})


SELECT 
    _DLT_PARENT_ID                          AS EVENT_DLT_ID,
    ATTRACTION__ATTRACTION_ID               AS ATTRACTION_ID, 
    ATTRACTION__LEGACY_ATTRACTION_ID        AS ATTRACTION_LEGACY_ID,
    ATTRACTION__ATTRACTION_NAME             AS ATTRACTION_NAME,
    ATTRACTION__ATTRACTION_URL              AS ATTRACTION_URL,
    ATTRACTION__CLASSIFICATION_SEGMENT_ID   AS SEGMENT_ID,
    ATTRACTION__CLASSIFICATION_SEGMENT      AS SEGMENT,
    ATTRACTION__CLASSIFICATION_GENRE_ID     AS GENRE_ID, 
    ATTRACTION__CLASSIFICATION_GENRE        AS GENRE,
    ATTRACTION__CLASSIFICATION_SUB_GENRE_ID AS SUB_GENRE_ID,
    ATTRACTION__CLASSIFICATION_SUB_GENRE    AS SUB_GENRE,
    ATTRACTION__CLASSIFICATION_TYPE_ID      AS CLASSIFICATION_TYPE_ID,
    ATTRACTION__CLASSIFICATION_TYPE         AS CLASSIFICATION_TYPE,
    ATTRACTION__CLASSIFICATION_SUB_TYPE_ID  AS CLASSIFICATION_SUB_TYPE_ID,
    ATTRACTION__CLASSIFICATION_SUB_TYPE     AS CLASSIFICATION_SUB_TYPE

FROM stage_events_attraction_hist
ORDER BY _DLT_PARENT_ID